### ISSUE TITLE
QAQC temperature data for release

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/2wp-temp-observations#26]
Because the temperature records are from many organizations, methods, etc., we expect that there will be quality issues in a minority of the records. These issues might include but are not limited to: 

- unit issues (reported in F or C, but don't make sense (e.g., units are C but temperature values > 40 deg).
- sensor out of water (river levels dropped, or someone took sensor out of water and forgot to turn it off). Patterns in data will be more similar to air temperature (so may be warmer in summer, or colder in winter)
- general data entry problems (order of magnitude wrong, dates with temperature that don't make sense, site ID or lat/long that may have been mis-entered.)
- others?

This is challenging to do at a national scale because it is hard to generalize what the temperature _should_ be at any given point and time. Sites that are further south will be warmer, but things like reservoirs and ground water inputs can make the temperature look different than you would expect (e.g., cooler temperatures in summer). The goal is to flag the egregious values.

**Comment by limnoliver** [comment]
The rough steps, as per our discussion:

1. Read in daily values, subset to a more reasonable size to experiment with.
2. Read in sites data to get lat/long. Create bins of 5 degrees of latitude to group data that should have similar data characteristics. 
3. Merge the bin column back to your subset of raw data. Group by bin and month, summarize to calculate your "outlier" values (e.g., 5th and 9th percentiles). Save this as a differently-named object than your subsetted raw data.
4. Merge the outlier statistics back into your subsetted raw data. These outlier statistics will be repeated for each observation in your latitude-month groups, but allows you to do a row-by-row check of whether we should call that point an outlier. Create a new column called "flag" that enters an "o" for outlier when the values is outside of those percentile statistics.

**Comment by RAtshan** [comment]
To evaluate the two methods above:
1.	Overall evaluation: We will look at the threshold levels to make sure that the mean, standard deviation, and cutoff limits are appropriate for the site’s location, source, and recorded temperatures (e.g month or month/day). 
2.	Specific site evaluation: selecting the sites with the highest counts of outliers, then we’ll use time-series plots to evaluate them. 
3.	Other evaluation techniques if needed:
a.	Time series plots to compare the two method’s thresholds (low-bound & up-bound). While considering the recorded temperature, means, etc. 
b.	We’ll select a few latitude bins (possibly associated with sites with the highest count of outliers) to compare the two methods.

**Comment by limnoliver** [comment]
Hi Rasha -- Some follow up questions to your proposal above.

- what are the "two methods"?
- for 1 - that's a lot of thresholds to look at. What specifically are you looking for, and can you/are you doing it programatically using rules? 
- for 2 - what are you shooting for here in terms of the number of sites you'll evaluate manually. Top 1%? 10 sites? site above a certain proportion of flagged data?

**Comment by RAtshan** [comment]
*Methods:*
To successfully QAQC the daily temperature data and flag egregious values correctly, I used the following approaches.

1.  Grouped the data by latitude bins and month as in the above steps explain: using this grouping approach we implemented the standard deviation method to calculate outlier’s thresholds (statistics). Then, we used the calculated threshold to determine whether each recorded temperature was an outlier or not. While evaluating the standard deviation method we noticed the variability within each latitude bin, the variability within a month, and variability from year to year. This variability was affecting the outlier's threshold calculations since we were not distinguishing between sites. E.g. during the winter months warm sites with higher temperatures were treated the same as other sites with normal (cooler) temperatures. Therefore, the warm sites were falsely flagged as outliers during the winter months even though the recorded temperatures were real data (not bad data) (see figure 1).  Figures 1 is representing the site with the highest count of outliers using the first approach. Finally, we used the current method to get a better understanding of the data’s variability and to find a more suitable grouping approach.

**Figure 1:**
![image](https://user-images.githubusercontent.com/65974907/94052950-49eb3480-fd9f-11ea-8e43-36b9d39213a4.png)

2. Grouped the date by site, source, month, and day: using this grouping we were able to overcome the variability challenges within the latitude bin and within each month. The reason we grouped by the source is that we noticed that different sources had different recorded temperatures on the same day (see tables 2 & 3). In this approach, we combined the standard deviation method with a fixed value for the cutoff limit to ensure that real data was not falsely marked as outliers (bad data) and to handle the low, high, and NA variance values.  First, we calculated the average and standard deviation for a particular day (e.g. March 8th) for all the years with recorded temps (e.g. 1984 – 2000) (see table 1). Then, we calculated the threshold to determine if a recorded temperature is an outlier or not, similar to the first approach. 

 Furthermore, we used the second approach to examine the site from figures 1 during the same year. Using the second approach the daily temperature from **USGS-10265150** site was not falsely flagged as outliers temperatures during the winter months (see figure 2 and table 1).

**Figure 2:**
![image](https://user-images.githubusercontent.com/65974907/94053568-18bf3400-fda0-11ea-8ed8-c503acd10360.png)

**Table 1:** 
![image](https://user-images.githubusercontent.com/65974907/94053774-63d94700-fda0-11ea-92bf-bcc1af543edf.png)

**Table 2:**
![image](https://user-images.githubusercontent.com/65974907/94053836-72276300-fda0-11ea-8ea5-685d7752af53.png)

**Table 3:**
![image](https://user-images.githubusercontent.com/65974907/94053883-7f445200-fda0-11ea-9ddf-fec13a18becc.png)

*Evaluation details:*
-  First, we created a subset of outliers observation from both approaches to look at which sites are being flagged as outliers, are theses outliers flagged correctly or false-positive outliers, the number of outliers from both approaches. 
- Looked at the sites with highest count of outliers then found further information about these sites. e.g.  We found information about **USGS-10265150** site on USGS website then compared the information with our findings. 
- Then, I looked at the results from the second approach manually. e.g. comparing the temperature mean to the observed temperature, investigated any means that seem suspicious when compared to temperature for that specific site, month, and day. E.g. table 1 is an example of how I investigated a specific site because the recoded temperature in row 232 doesn't align with the calculated mean. We also looked to check for false-positives and false-negatives outlier detection. 
-  Next, I will programmatically find the  10 sites with the highest count of outliers and evaluate them using time-series plots. Then, investigate any suspicious temperature or means manually and programmatically.  
If we feel that we need to further investigate the grouping approaches and /or the results in this then we will.
