### ISSUE TITLE
Create examples of how the reach data can be visualized

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/2wp-temp-observations#6]
to convey the density of data available by reach

**Comment by limnoliver** [comment]
An MVP for this is a visualization of the Delaware basin modeled temperature output from SNTemp, combined with observed temperature records and the hydrologic network. See Jordan's example GIF I've pasted [here](https://docs.google.com/document/d/1s2-iN0KsnIHjYpFyuY_8NFiOQSUHMJYFFUMAYH_PbBc/edit). One idea would be to overlay observed temperatures as points using the same color scheme as the reaches (which is the modeled temp) so you can visualize how different the modeled and observed temperatures are. 

A bonus on top if this would be a complimentary sub-panel in the GIF, that adds points to a scatterplot in each time step that shows modeled vs observed data (this is where the data and model output have to be linked by reach ID). 

This task would require the following:
1. Crosswalk between WQP/NWIS data and the hydrologic network (right now, just the Delaware)
2. *Filter all observed data to Delaware sites
3. *Resolve Delaware observed data to a [mean and max -- need to check what the model output is] daily value.
4. *Merge modeled output and observed data so each row has reachID, date, temp_modeled, temp_observed. This should retain all of the modeled data; there will be many missing vals in temp_observed. 
5. Create the animated viz at the (daily) time step. May be useful to initially filter this to a time period where we have a lot of data (since the modeled output has many years).

Most of this can be done outside of the repository initially - as (depending on who is doing the task) it doesn't make sense to learn `scipiper` for this task. I'm happy to do the extra work to formally incorporate it into the pipeline.  

* I will work on these once the addressing is done.

**Comment by abriggs-usgs** [comment]
This one has been buried in the backlog for nearly a year, but it seems like it may be relevant to some of the new WBEEP Temperature Prediction work. I am will relabel this to WBEEP temp for reevaluation.
